### ISSUE TITLE
Check_rc and clean

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/CampBot#12]
It would be nice if the procedures check_rec and clean do not proceed the "Point Cardinaux" correction in the "Ressource externe" section. 

See https://forum.camptocamp.org/t/aux-dresseurs-des-bots/255904

In fact, titles of books or external articles should only be in this section, and should not be modified.

**Comment by cbeauchesne** [comment]
discussion : https://forum.camptocamp.org/t/corrections-automatiques-dans-le-topoguide/214780/392?u=charlesb

**Comment by cbeauchesne** [comment]
It's juste removing `external_resources` field
