### ISSUE TITLE
check_rec and forum update

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/CampBot#20]
robot unable to post on the forum since the forum update:

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/campbot", line 10, in <module>
>     sys.exit(main_entry_point())
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/campbot/__main__.py", line 66, in main_entry_point
>     main(docopt(__doc__))
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/campbot/__main__.py", line 75, in main
>     ask_before_saving=not args["--batch"])
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/campbot/checkers.py", line 198, in check_recent_changes
>     bot.forum.post_message("\n".join(messages), check_message_url)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/campbot/core.py", line 310, in post_message
>     self.post("/posts", {"topic_id": topic_id, "raw": message})
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/campbot/core.py", line 80, in post
>     res.raise_for_status()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://forum.camptocamp.org/posts
>

**Comment by cbeauchesne** [comment]
I think it was a temporary issue on forum, I successfuly ran it : 

https://forum.camptocamp.org/t/topoguide-verifications-automatiques/201480/1015?u=charlesb
