### ISSUE TITLE
[Bug] Problem with accents

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/CampBot#3]
> ^^^ root.locales[0].description :
> - On continue en face pour descendre sur El Draguillo. Un peu plus bas dans la descente, deux possibilitée:
> ? ^
> + On continue en face pour descendre sur El Draguillo. Un peu plus bas dans la descente, deux possibilitéśe:
> ? ^^
> Save https://www.camptocamp.org/routes/1079822 : Accents manquants, Diverses fautes, y/[n] ?

I could not see any problem in the article giving the corrections. 

Maybe it is related to the fact that the _é_ was entered as _ '+e _ ?

**Comment by BorutK** [comment]
----
It may be the colon (**:**) which interferes in some way (there has already been a colon question in the past). 

----
- With the *Automatic corrections in the guidebook* article, the correction 

      deux possibilitée >> deux possibilités
is active, in the *Diverses fautes* section. 

> Also check the *Accents manquants* section and the *Diverses fautes* section for "possibilités".

**Comment by cbeauchesne** [comment]
Really really weird. On the original document, it's not a "*e accent aigu*", but a "e" followed by the generic diacritic accent : https://fr.wikipedia.org/wiki/Table_des_caract%C3%A8res_Unicode/U0300 => character code `U+0301`.

If I print the expected word `possibilités' , it should be : `possibilit\u00e9e`, and  `\u00e9` stands for `é`. 

But in the original document, it's `deux possibilite\u0301e`, and `e\u0301` stands for `e` modified by `\u0301`.

And bad luck, the engine that process corrections does not understand at all the char `\u0301`, and think it's a word boundary. In consequence, here is the substitutions used, in this order : 

    possibilite  >> possibilité  
    deux possibilité  >> possibilités  
 
I'll add a core substitution in the processor for replacement of this weird char...
